# Generated by Django 3.0.6 on 2020-06-04 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='status_taex',
            new_name='status_text',
        ),
    ]
